# Setup
title: Sihan's Blog
description: Neither do men light a candle, and put it under a bushel, but on a candlestick; and it giveth light unto all that are in the house.
url: https://Sihan0229.github.io
# avatar: /ava.jpg
paginate: 5
permalink: 
cover_image: /gsh_bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Sihan Gao
  links:
    - https://x.com/Sihan0229
    - https://github.com/Sihan0229
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Sihan Gao
  url: https://github.com/Sihan0229
  email: sihangao2004@gmail.com
